extends: default

rules:
  document-start: disable

  line-length: disable

  indentation:
    level: error
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  comments-indentation: disable

  empty-lines:
    level: error
    max: 1

  truthy:
    level: error
    allowed-values:
      - "true"
      - "false"
    check-keys: false

  quoted-strings:
    level: error
    quote-type: double
    required: only-when-needed

  trailing-spaces: enable
  key-duplicates: enable
  new-line-at-end-of-file: enable
