
[colors]
all_cpu_color = "#dc8a78"
arc_color = "#04a5e5"
avg_cpu_color = "#e64553"
border_color = "#acb0be"
cpu_core_colors = [
  "#209fb5",
  "#40a02b",
  "#8839ef",
  "#d20f39",
  "#df8e1d",
  "#fe640b",
]
cursor_color = "#ea76cb"
gpu_core_colors = [
  "#209fb5",
  "#40a02b",
  "#8839ef",
  "#d20f39",
  "#df8e1d",
  "#fe640b",
]
graph_color = "#6c6f85"
high_battery_color = "#40a02b"
highlighted_border_color = "#ea76cb"
low_battery_color = "#d20f39"
medium_battery_color = "#df8e1d"
ram_color = "#40a02b"
rx_color = "#40a02b"
selected_bg_color = "#8839ef"
selected_text_color = "#dce0e8"
swap_color = "#fe640b"
table_header_color = "#dc8a78"
text_color = "#4c4f69"
tx_color = "#d20f39"
widget_title_color = "#dd7878"
