"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](pink)\
$os\
$username\
[](fg:pink bg:yellow)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:lavender)\
$c\
$cmake\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:lavender bg:mauve)\
$cmd_duration\
[](fg:mauve bg:overlay0)\
$time\
[ ](fg:overlay0)
"""

add_newline = true

palette = "catppuccin_latte"

[palettes.catppuccin_latte]
base      = "#eff1f5"
blue      = "#1e66f5"
crust     = "#dce0e8"
flamingo  = "#dd7878"
green     = "#40a02b"
lavender  = "#7287fd"
mantle    = "#e6e9ef"
maroon    = "#e64553"
mauve     = "#8839ef"
overlay0  = "#9ca0b0"
overlay1  = "#8c8fa1"
overlay2  = "#7c7f93"
peach     = "#fe640b"
pink      = "#ea76cb"
red       = "#d20f39"
rosewater = "#dc8a78"
sapphire  = "#209fb5"
sky       = "#04a5e5"
subtext0  = "#6c6f85"
subtext1  = "#5c5f77"
surface0  = "#ccd0da"
surface1  = "#bcc0cc"
surface2  = "#acb0be"
teal      = "#179299"
text      = "#4c4f69"
yellow    = "#df8e1d"

[os]
disabled = false
style    = "fg:text bg:pink"

[os.symbols]
Alpine           = ""
Amazon           = ""
Android          = ""
Arch             = "󰣇"
Artix            = "󰣇"
CentOS           = ""
Debian           = "󰣚"
Fedora           = "󰣛"
Gentoo           = "󰣨"
Linux            = "󰌽"
Macos            = "󰀵"
Manjaro          = ""
Mint             = "󰣭"
Raspbian         = "󰐿"
RedHatEnterprise = "󱄛"
Redhat           = "󱄛"
SUSE             = ""
Ubuntu           = "󰕈"
Windows          = "󰍲"

[username]
format      = "[ $user ]($style)"
show_always = true
style_root  = "bg:pink fg:text"
style_user  = "bg:pink fg:text"

[directory]
format            = "[ $path ]($style)"
style             = "fg:text bg:yellow"
truncate_to_repo  = false
truncation_length = 100
truncation_symbol = "…/"

[git_branch]
format = '[[ $symbol $branch ](fg:text bg:green)]($style)'
style  = "bg:green"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind )](fg:text bg:green)]($style)'
style  = "bg:green"

[nodejs]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[c]
detect_extensions = ['c', 'cc', 'cpp', 'h', 'hpp']
format            = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style             = "bg:lavender"
symbol            = ""

[cmake]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[rust]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[golang]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[php]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[java]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = " "

[kotlin]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[haskell]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[python]
format = '[[ $symbol( $version) ](fg:text bg:lavender)]($style)'
style  = "bg:lavender"
symbol = ""

[docker_context]
format = '[[ $symbol( $context) ](fg:text bg:mauve)]($style)'
style  = "bg:mauve"
symbol = ""

[cmd_duration]
min_time = 1
# show_notifications = true
# style = "bg:mauve"
format = '[[ 󰔛 $duration ](fg:crust bg:mauve)]($style)'

[time]
disabled    = false
format      = '[[  $time ](fg:text bg:overlay0)]($style)'
style       = "bg:overlay0"
time_format = "%R"

[line_break]
disabled = true

[character]
disabled                  = false
error_symbol              = '[](bold fg:color_red)'
success_symbol            = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol     = '[](bold fg:color_purple)'
vimcmd_symbol             = '[](bold fg:color_green)'
vimcmd_visual_symbol      = '[](bold fg:yellow)'
