"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:mauve)\
[](fg:lavender bg:mauve)\
$os\
$directory\
[](fg:blue bg:lavender)\
$git_branch$git_status\
[](fg:sky bg:blue)\
$c$cmake$rust$lua$python\
[](fg:teal bg:sky)\
$time\
[](fg:sapphire bg:teal)\
$cmd_duration\
$character
[❯ ](peach)
"""

add_newline = true
palette     = "catppuccin_latte"

[line_break]
disabled = true

[palettes.catppuccin_latte]
base      = "#eff1f5"
blue      = "#1e66f5"
crust     = "#dce0e8"
flamingo  = "#dd7878"
green     = "#40a02b"
lavender  = "#7287fd"
mantle    = "#e6e9ef"
maroon    = "#e64553"
mauve     = "#8839ef"
overlay0  = "#9ca0b0"
overlay1  = "#8c8fa1"
overlay2  = "#7c7f93"
peach     = "#fe640b"
pink      = "#ea76cb"
red       = "#d20f39"
rosewater = "#dc8a78"
sapphire  = "#209fb5"
sky       = "#04a5e5"
subtext0  = "#6c6f85"
subtext1  = "#5c5f77"
surface0  = "#ccd0da"
surface1  = "#bcc0cc"
surface2  = "#acb0be"
teal      = "#179299"
text      = "#4c4f69"
yellow    = "#df8e1d"

[c]
detect_extensions = ["c", "cc", "cpp", "h", "hpp"]
detect_files      = ["CMakeLists.txt"]
format            = "[$symbol $version ]($style)"
style             = "fg:mantle bg:sky"
symbol            = ""

[cmake]
format = "[$symbol $version ]($style)"
style  = "fg:mantle bg:sky"
symbol = ""

[rust]
format = "[$symbol $version ]($style)"
style  = "fg:mantle bg:sky"
symbol = ""

[python]
format = "[$symbol $version ]($style)"
style  = "fg:mantle bg:sky"
symbol = ""

[lua]
format = "[$symbol $version ]($style)"
style  = "fg:mantle bg:sky"
symbol = ""

[git_branch]
format = "[ $symbol $branch]($style)"
style  = "fg:mantle bg:blue"
symbol = ""

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style  = "fg:mantle bg:blue"

[os]
disabled = false
format   = "[$symbol ]($style)"
style    = "fg:mantle bg:lavender"

[os.symbols]
Arch   = "󰣇"
Ubuntu = "󰕈"

[directory]
format            = "[$path ]($style)"
style             = "fg:mantle bg:lavender"
truncate_to_repo  = false
truncation_length = 100
truncation_symbol = "…/"

[cmd_duration]
format             = "[ 󰔛 $duration ]($style)"
min_time           = 1
show_notifications = true
style              = "fg:mantle bg:sapphire"

[time]
disabled    = false
format      = "[  $time ]($style)"
style       = "fg:mantle bg:teal"
time_format = "%R"

[character]
disabled       = false
error_symbol   = "[[](fg:red bg:sapphire)](red)"
success_symbol = "[[](fg:green bg:sapphire)](green)"
