local options = {
  backup = false,
  clipboard = "unnamedplus",
  cmdheight = 1,
  completeopt = { "menuone", "noselect" },
  conceallevel = 0,
  encoding = "utf-8",
  fileencoding = "utf-8",
  foldmethod = "manual",
  foldexpr = "",
  hidden = true,
  hlsearch = true,
  ignorecase = true,
  mouse = "a",
  pumheight = 10,
  showmode = false,
  smartcase = true,
  smartindent = true,
  splitbelow = false,
  splitright = false,
  swapfile = false,
  timeoutlen = 1000,
  title = true,
  -- undodir = undodir,
  undofile = true,
  updatetime = 100,
  writebackup = false,
  expandtab = true,
  shiftwidth = 2,
  tabstop = 2,
  showtabline = 2,
  cursorline = true,
  number = true,
  relativenumber = false,
  numberwidth = 4,
  signcolumn = "yes",
  wrap = true,
  -- shade_file=,
  scrolloff = 8,
  sidescrolloff = 8,
  showcmd = false,
  ruler = false,
  laststatus = 3,

  spelllang = "cjk",
  shortmess = "cIF",
  whichwrap = "<,>,[,],h,l",
}

for k, v in pairs(options) do
  vim.opt[k] = v
end
