[general]
import = ["~/.config/alacritty/catppuccin_latte.toml"]

[window]
opacity = 1.0

[font]
size = 9

[font.normal]
family = "SauceCodeProNerdFont"
style  = "Regular"

[font.bold]
family = "SauceCodeProNerdFont"
style  = "Bold"

[font.italic]
family = "SauceCodeProNerdFont"
style  = "Italic"

[font.bold_italic]
family = "SauceCodeProNerdFont"
style  = "Bold Italic"
