"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:mauve)\
[](fg:lavender bg:mauve)\
$os\
$directory\
[](fg:blue bg:lavender)\
$git_branch$git_status\
[](fg:sky bg:blue)\
$c$cmake$rust$lua$python\
[](fg:teal bg:sky)\
$time\
[](fg:sapphire bg:teal)\
$cmd_duration\
$character
[❯ ](peach)
"""

palette = "catppuccin_latte"
add_newline = true

[line_break]
disabled = true

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[c]
style = "fg:mantle bg:sky"
symbol = ""
format = "[$symbol $version ]($style)"
detect_extensions = ["c", "h", "cpp", "hpp", "cc"]
detect_files = ["CMakeLists.txt"]

[cmake]
symbol = ""
style = "fg:mantle bg:sky"
format = "[$symbol $version ]($style)"

[rust]
symbol = ""
style = "fg:mantle bg:sky"
format = "[$symbol $version ]($style)"

[python]
symbol = ""
style = "fg:mantle bg:sky"
format = "[$symbol $version ]($style)"

[lua]
symbol = ""
style = "fg:mantle bg:sky"
format = "[$symbol $version ]($style)"

[git_branch]
symbol = ""
style = "fg:mantle bg:blue"
format = "[ $symbol $branch]($style)"

[git_status]
style = "fg:mantle bg:blue"
format = "[$all_status$ahead_behind ]($style)"

[os]
disabled = false
style = "fg:mantle bg:lavender"
format = "[$symbol ]($style)"

[os.symbols]
Arch = "󰣇"
Ubuntu = "󰕈"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"
style = "fg:mantle bg:lavender"
format = "[$path ]($style)"

[cmd_duration]
min_time = 1
show_notifications = true
style = "fg:mantle bg:sapphire"
format = "[ 󰔛 $duration ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:mantle bg:teal"
format = "[  $time ]($style)"

[character]
disabled = false
success_symbol = "[[](fg:green bg:sapphire)](green)"
error_symbol = "[[](fg:red bg:sapphire)](red)"
