name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-stylua-2.3.0
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install stylua
        run: |
          if ! command -v stylua >/dev/null || [[ "$(stylua --version)" != "stylua 2.3.0" ]]; then
            cargo install stylua --version 2.3.0 --locked
          fi

      - run: find . -type f -name "*.lua" -print0 | xargs -0 stylua --check

  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-taplo-0.10.0
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install taplo
        run: |
          if ! command -v taplo >/dev/null || [[ "$(taplo --version)" != "taplo 0.10.0" ]]; then
            cargo install taplo-cli --version 0.10.0 --locked
          fi

      - run: taplo fmt --check

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install yamllint==1.37.1

      - run: yamllint .
