name: ci

on:
  push:
    branches: ["v2"]
  schedule:
    - cron: '0 0 1 * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo install taplo-cli --locked
      - run: taplo fmt --check

  lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo install stylua
      - run: find . -type f -name "*.lua" -print0 | xargs -0 stylua --check
