name: Check editorconfig

on:
  workflow_call:

jobs:
  editorconfig-checker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.5

      - run: |
          go install github.com/editorconfig-checker/editorconfig-checker/v3/cmd/editorconfig-checker@v3.6.1

      - run: editorconfig-checker -format github-actions
