name: Editorconfig lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  editorconfig-checker:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2
      - name: Run editorconfig-checker
        run: editorconfig-checker
