name: Lint

on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lua:
    uses: ./.github/workflows/lua.yaml
  toml:
    uses: ./.github/workflows/toml.yaml
  yaml:
    uses: ./.github/workflows/yaml.yaml
  sh-bash:
    uses: ./.github/workflows/sh-bash.yaml
  zsh:
    uses: ./.github/workflows/zsh.yaml
  markdown:
    uses: ./.github/workflows/markdown.yaml
  json:
    uses: ./.github/workflows/json.yaml
  editorconfig:
    uses: ./.github/workflows/editorconfig.yaml
