name: "Lua lint"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  luacheck:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false
      - uses: "lunarmodules/luacheck@v1"
        with:
          args: "--codes --ranges --no-color ."

  stylua:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false
      - uses: "JohnnyMorganz/stylua-action@v5"
        with:
          token: "${{ github.token }}"
          version: "2.4.1"
          args: "--check --output-format=unified ."
