name: Lint lua

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: |
          sudo apt update
          sudo apt install -y luajit luarocks
          sudo luarocks install luacheck
      - run: luacheck --codes --ranges .

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-stylua-2.3.0
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install stylua
        run: |
          if ! command -v stylua >/dev/null || [[ "$(stylua --version)" != "stylua 2.3.0" ]]; then
            cargo install stylua --version 2.3.0 --locked
          fi

      - run: find . -type f -name "*.lua" -print0 | xargs -0 stylua --check
