name: Lint Markdown

on:
  workflow_call:

jobs:
  markdownlint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run markdownlint
        run: |
          find . -type f -name "*md" -print0 | xargs -0 npx markdownlint-cli2@0.20.0 --config .markdownlint.json
