name: Markdown Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  markdownlint-cli2:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"
